import { GoogleGenAI } from "@google/genai";
import { NextRequest, NextResponse } from "next/server";

function getGenAIClient(): GoogleGenAI {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error(
      "GEMINI_API_KEY is not set. If you are hosting on Vercel, please add GEMINI_API_KEY to your Vercel Project Settings > Environment Variables."
    );
  }
  return new GoogleGenAI({ apiKey });
}

/**
 * Sanitizes and validates raw OBJ text generated by LLMs to prevent
 * missing indices, NaN coordinates, and malformed face references.
 */
function sanitizeObj(raw: string): string {
  if (!raw) return "";

  // Strip markdown code fences
  let text = raw.replace(/^```(obj|wavefront|txt)?\n/gim, '').replace(/\n```$/gm, '').trim();

  const lines = text.split(/\r?\n/);
  const cleanLines: string[] = [];
  let vertexCount = 0;

  // First pass: collect vertices and validate
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const parts = trimmed.split(/\s+/);
    const type = parts[0].toLowerCase();

    if (type === 'v') {
      // Vertex: v x y z [r g b]
      const coords = parts.slice(1).map(Number);
      if (coords.length >= 3 && coords.slice(0, 3).every(n => !isNaN(n) && isFinite(n))) {
        vertexCount++;
        if (coords.length >= 6 && coords.slice(3, 6).every(n => !isNaN(n) && isFinite(n))) {
          cleanLines.push(`v ${coords[0]} ${coords[1]} ${coords[2]} ${coords[3]} ${coords[4]} ${coords[5]}`);
        } else {
          cleanLines.push(`v ${coords[0]} ${coords[1]} ${coords[2]}`);
        }
      }
    } else if (type === 'vn') {
      // Normal: vn x y z
      const coords = parts.slice(1).map(Number);
      if (coords.length >= 3 && coords.slice(0, 3).every(n => !isNaN(n) && isFinite(n))) {
        cleanLines.push(`vn ${coords[0]} ${coords[1]} ${coords[2]}`);
      }
    } else if (type === 'vt') {
      // UV: vt u v
      const coords = parts.slice(1).map(Number);
      if (coords.length >= 2 && coords.slice(0, 2).every(n => !isNaN(n) && isFinite(n))) {
        cleanLines.push(`vt ${coords[0]} ${coords[1]}`);
      }
    } else if (type === 'g' || type === 'o') {
      const name = parts.slice(1).join('_').replace(/[^a-zA-Z0-9_-]/g, '') || 'part';
      cleanLines.push(`${type} ${name}`);
    } else if (type === 'f') {
      // Face definitions
      const faceTokens = parts.slice(1);
      const validTokens: string[] = [];

      for (const token of faceTokens) {
        const sub = token.split('/');
        const vIdx = parseInt(sub[0], 10);
        if (!isNaN(vIdx)) {
          // Handle relative indices (negative) or 1-based indices
          const actualIdx = vIdx < 0 ? vertexCount + vIdx + 1 : vIdx;
          if (actualIdx >= 1 && actualIdx <= vertexCount) {
            // Keep clean vertex index only for stability
            validTokens.push(`${actualIdx}`);
          }
        }
      }

      // Triangulate if more than 3 vertices
      if (validTokens.length === 3) {
        cleanLines.push(`f ${validTokens[0]} ${validTokens[1]} ${validTokens[2]}`);
      } else if (validTokens.length === 4) {
        cleanLines.push(`f ${validTokens[0]} ${validTokens[1]} ${validTokens[2]}`);
        cleanLines.push(`f ${validTokens[0]} ${validTokens[2]} ${validTokens[3]}`);
      } else if (validTokens.length > 4) {
        for (let i = 1; i < validTokens.length - 1; i++) {
          cleanLines.push(`f ${validTokens[0]} ${validTokens[i]} ${validTokens[i + 1]}`);
        }
      }
    }
  }

  return cleanLines.join('\n');
}

export async function POST(req: NextRequest) {
  try {
    const { prompt, model: requestedModel } = await req.json();

    if (!prompt) {
      return NextResponse.json({ error: "Prompt is required" }, { status: 400 });
    }

    const ai = getGenAIClient();

    const systemInstruction = `You are a professional low-poly 3D OBJ model generator.
Create a clean, symmetrical, low-poly Wavefront .obj file representing the requested object.

Strict Rules:
1. Output ONLY valid .obj lines. Do not wrap in markdown or add explanations.
2. Group the model into logical parts with 'g group_name' (e.g., 'g blade', 'g hilt', 'g handle', 'g gem').
3. For each vertex 'v', provide 3 floating point numbers: 'v x y z'. You can optionally append RGB vertex colors (e.g. 'v x y z r g b' with 0.0 to 1.0).
4. Faces MUST use 1-based indexing referencing ONLY vertices that have already been declared.
5. All faces must be triangles ('f v1 v2 v3') or quads ('f v1 v2 v3 v4').
6. Keep vertex count compact (between 50 and 600 vertices) to ensure high speed and stability.`;

    const modelsToTry = [
      requestedModel || "gemini-3.6-flash",
      "gemini-2.5-flash",
      "gemini-2.5-pro"
    ].filter(Boolean);

    let response;
    let lastError;

    for (const modelName of modelsToTry) {
      try {
        response = await ai.models.generateContent({
          model: modelName,
          contents: `Generate a 3D model in OBJ format for: ${prompt}`,
          config: {
            systemInstruction,
            temperature: 0.1,
          }
        });
        if (response && response.text && response.text.includes('v ') && response.text.includes('f ')) {
          break;
        }
      } catch (err) {
        console.warn(`Model ${modelName} failed, trying next...`, err);
        lastError = err;
      }
    }

    if (!response || !response.text) {
      throw lastError || new Error("Failed to generate 3D model from AI models.");
    }

    const sanitizedObj = sanitizeObj(response.text);

    if (!sanitizedObj.includes('v ') || !sanitizedObj.includes('f ')) {
      throw new Error("Generated 3D model geometry was incomplete. Please try again with a descriptive prompt.");
    }

    return NextResponse.json({ obj: sanitizedObj });
  } catch (error: any) {
    console.error("Error generating 3D model:", error);
    const message = error?.message || "Failed to generate 3D model";
    return NextResponse.json(
      { error: message.includes("429") || message.includes("quota") ? "Rate limit reached. Please wait a moment and try again." : message },
      { status: 500 }
    );
  }
}

